version: "3.9"

services:
  gpt_vs_human_compare:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gpt_vs_human_compare
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    command:
      [
        "python",
        "${SCRIPT_TO_RUN}"
      ]
